from config import CONFIG
from event_keys import (
    ARCHIMEDES_KEY, CURIE_KEY, DALY_KEY, GALILEO_KEY,
    HOPPER_KEY, JOHNSON_KEY, MILSTEIN_KEY, NEWTON_KEY,
)

SPREADSHEET_ID = CONFIG.spreadsheet_id
PAST_MATCHES_SHEET_ID = CONFIG.past_matches_sheet_id
UPCOMING_MATCHES_SHEET_ID = CONFIG.upcoming_matches_sheet_id

ARCHIMEDES_RANKINGS_SHEET_ID = CONFIG.archimedes_rankings_sheet_id
CURIE_RANKINGS_SHEET_ID = CONFIG.curie_rankings_sheet_id
DALY_RANKINGS_SHEET_ID = CONFIG.daly_rankings_sheet_id
GALILEO_RANKINGS_SHEET_ID = CONFIG.galileo_rankings_sheet_id
HOPPER_RANKINGS_SHEET_ID = CONFIG.hopper_rankings_sheet_id
JOHNSON_RANKINGS_SHEET_ID = CONFIG.johnson_rankings_sheet_id
MILSTEIN_RANKINGS_SHEET_ID = CONFIG.milstein_rankings_sheet_id
NEWTON_RANKINGS_SHEET_ID = CONFIG.newton_rankings_sheet_id

DIVISION_RANKINGS_SHEET_IDS = {
    ARCHIMEDES_KEY: ARCHIMEDES_RANKINGS_SHEET_ID,
    CURIE_KEY: CURIE_RANKINGS_SHEET_ID,
    DALY_KEY: DALY_RANKINGS_SHEET_ID,
    GALILEO_KEY: GALILEO_RANKINGS_SHEET_ID,
    HOPPER_KEY: HOPPER_RANKINGS_SHEET_ID,
    JOHNSON_KEY: JOHNSON_RANKINGS_SHEET_ID,
    MILSTEIN_KEY: MILSTEIN_RANKINGS_SHEET_ID,
    NEWTON_KEY: NEWTON_RANKINGS_SHEET_ID,
}
